Repository PQCA/cbomkit, pull requests merged in 2025-02, with the labels that each got.

#110 Update dependecies frontend, update helm chart
  chart/values.yaml
  frontend/package-lock.json
  src/main/java/com/ibm/usecases/scanning/services/pkg/PackageFinderService.java
Labels: enhancement, dependencies

#111 update readme, update sbom
  README.md
  bom/bom.json
Labels: documentation

#113 Downgrade quarkus version
  pom.xml
Labels: bug

#132 upgrade to sonar-cryptography-1.4.2 and giturl normalization
  frontend/src/helpers/scan.js
  pom.xml
  src/main/java/com/ibm/domain/scanning/GitUrl.java
  src/main/java/com/ibm/usecases/scanning/processmanager/ScanProcessManager.java
Labels: dependencies

#133 Update example CBOMs
  example/flick-cbom.json
  example/kafka-cbom.json
  example/keycloak-cbom.json
Labels: enhancement
