Repository PQCA/cbomkit, pull requests merged in 2025-03, with the labels that each got.

#139 Update README.md
  README.md
Labels: documentation

#149 Hotfix: disabled python indexing and scanning
  pom.xml
  src/main/java/com/ibm/usecases/scanning/processmanager/ScanProcessManager.java
Labels: bug

#150 Update make file, update readme
  Makefile
  README.md
Labels: documentation

#152 Update README.md
  README.md
Labels: documentation

#155 Fixed indexing: find deep modules and order indexed files
  src/main/java/com/ibm/usecases/scanning/services/indexing/IndexingService.java
  src/main/java/com/ibm/usecases/scanning/services/indexing/JavaIndexService.java
  src/main/java/com/ibm/usecases/scanning/services/indexing/PythonIndexService.java
  src/main/java/com/ibm/usecases/scanning/services/scan/java/JavaAstScannerExtension.java
Labels: bug, enhancement

#156 Feature/add unit tests and code improvements
  frontend/src/components/global/NotificationsView.vue
  frontend/src/helpers/cbom.js
  frontend/src/helpers/scan.js
  frontend/src/model.js
  pom.xml
  src/main/java/com/ibm/infrastructure/Configuration.java
  src/main/java/com/ibm/infrastructure/progress/ProgressMessageType.java
  src/main/java/com/ibm/infrastructure/scanning/IScanConfiguration.java
  src/main/java/com/ibm/usecases/scanning/processmanager/ScanProcessManager.java
  src/main/java/com/ibm/usecases/scanning/services/indexing/IBuildType.java
  src/main/java/com/ibm/usecases/scanning/services/indexing/IndexingService.java
  src/main/java/com/ibm/usecases/scanning/services/indexing/JavaBuildType.java
  src/main/java/com/ibm/usecases/scanning/services/indexing/JavaIndexService.java
  src/main/java/com/ibm/usecases/scanning/services/indexing/PythonBuildType.java
  src/main/java/com/ibm/usecases/scanning/services/indexing/PythonIndexService.java
  src/main/java/com/ibm/usecases/scanning/services/scan/java/JavaScannerService.java
  src/test/java/com/ibm/architecture/DomainTest.java
  src/test/java/com/ibm/usecases/scanning/services/indexing/JavaIndexServiceTest.java
  src/test/java/com/ibm/usecases/scanning/services/indexing/PythonIndexServiceTest.java
  src/test/java/com/ibm/usecases/scanning/services/scan/JavaScannerServiceTest.java
  src/test/java/com/ibm/usecases/scanning/services/scan/PythonScannerServiceTest.java
  src/test/java/com/ibm/utils/AssetableProgressDispatcher.java
  src/test/testdata/java/keycloak/crypto/default/pom.xml
  src/test/testdata/java/keycloak/crypto/default/src/main/java/org/keycloak/crypto/def/AesKeyWrapAlgorithmProvider.java
  src/test/testdata/java/keycloak/crypto/default/src/main/java/org/keycloak/crypto/def/BCCertificateUtilsProvider.java
  src/test/testdata/java/keycloak/crypto/default/src/main/java/org/keycloak/crypto/def/BCECDSACryptoProvider.java
  src/test/testdata/java/keycloak/crypto/default/src/main/java/org/keycloak/crypto/def/BCEcdhEsAlgorithmProvider.java
  src/test/testdata/java/keycloak/crypto/default/src/main/java/org/keycloak/crypto/def/BCOCSPProvider.java
  src/test/testdata/java/keycloak/crypto/default/src/main/java/org/keycloak/crypto/def/BCPemUtilsProvider.java
  src/test/testdata/java/keycloak/crypto/default/src/main/java/org/keycloak/crypto/def/BCUserIdentityExtractorProvider.java
  src/test/testdata/java/keycloak/crypto/default/src/main/java/org/keycloak/crypto/def/DefaultCryptoProvider.java
  src/test/testdata/java/keycloak/crypto/default/src/main/java/org/keycloak/crypto/def/DefaultRsaKeyEncryption256JWEAlgorithmProvider.java
  src/test/testdata/java/keycloak/crypto/default/src/main/java/org/keycloak/crypto/def/DefaultRsaKeyEncryptionJWEAlgorithmProvider.java
  src/test/testdata/java/keycloak/crypto/default/src/main/java/org/keycloak/crypto/hash/Argon2Parameters.java
  src/test/testdata/java/keycloak/crypto/default/src/main/java/org/keycloak/crypto/hash/Argon2PasswordHashProvider.java
  src/test/testdata/java/keycloak/crypto/default/src/main/java/org/keycloak/crypto/hash/Argon2PasswordHashProviderFactory.java
  src/test/testdata/java/keycloak/crypto/pom.xml
  src/test/testdata/java/keycloak/services/pom.xml
  src/test/testdata/java/keycloak/services/src/main/java/org/keycloak/WebAuthnConstants.java
  src/test/testdata/java/keycloak/services/src/main/java/org/keycloak/authentication/RequiredActionContextResult.java
  src/test/testdata/java/keycloak/services/src/main/java/org/keycloak/authentication/actiontoken/TokenUtils.java
  src/test/testdata/java/keycloak/services/src/main/java/org/keycloak/authentication/actiontoken/execactions/ExecuteActionsActionToken.java
  src/test/testdata/java/keycloak/services/src/main/java/org/keycloak/authentication/actiontoken/execactions/ExecuteActionsActionTokenHandler.java
  src/test/testdata/java/keycloak/services/src/main/java/org/keycloak/authentication/actiontoken/more/idpverifyemail/IdpVerifyAccountLinkActionToken.java
  src/test/testdata/java/keycloak/services/src/main/java/org/keycloak/authentication/actiontoken/more/idpverifyemail/IdpVerifyAccountLinkActionTokenHandler.java
  src/test/testdata/java/keycloak/services/src/main/java/org/keycloak/authentication/authenticators/AttemptedAuthenticator.java
  src/test/testdata/java/keycloak/services/src/main/java/org/keycloak/authentication/authenticators/access/AllowAccessAuthenticator.java
  src/test/testdata/java/keycloak/services/src/main/java/org/keycloak/authentication/authenticators/access/AllowAccessAuthenticatorFactory.java
  src/test/testdata/java/keycloak/services/src/main/java/org/keycloak/authentication/authenticators/access/DenyAccessAuthenticator.java
  src/test/testdata/java/keycloak/services/src/main/java/org/keycloak/authentication/authenticators/access/DenyAccessAuthenticatorFactory.java
  src/test/testdata/java/keycloak/services/src/main/java/org/keycloak/connections/httpclient/DefaultHttpClientFactory.java
  src/test/testdata/java/keycloak/services/src/main/java/org/keycloak/connections/httpclient/HttpClientBuilder.java
  src/test/testdata/java/keycloak/services/src/main/java/org/keycloak/connections/httpclient/ProxyMappings.java
  src/test/testdata/java/keycloak/services/src/main/java/org/keycloak/connections/httpclient/ProxyMappingsAwareRoutePlanner.java
  src/test/testdata/java/keycloak/services/src/main/java/org/keycloak/connections/httpclient/SafeBasicResponseHandler.java
  src/test/testdata/java/keycloak/services/src/main/java/org/keycloak/connections/httpclient/SafeHttpEntity.java
  src/test/testdata/java/plain/JavaCrypto.java
  src/test/testdata/python/pyca/generate_key.py
Labels: bug, enhancement
